/** OpenAPI registrations for /commissions, /settlements, /ledger, /invoices, /admin/invoices and /expenses (api.md §8.19–§8.22). */
import { z } from 'zod';
import {
  addSettlementLineBody, approveSettlementBody, clearanceQueueQuery, commissionEarningsQuery, commissionPreviewBody, createCommissionRuleBody, createExpenseBody, createInvoiceBody, createSettlementBody, creditNoteBody, debitNoteBody, expenseSummaryQuery, generateInvoicesBody, idParams,
  listCommissionRulesQuery, listExpensesQuery, listInvoiceLinesQuery, listInvoicesQuery, listLedgerEntriesQuery, listSettlementsQuery, ownerIdParams, patchCommissionRuleBody, patchExpenseBody, paySettlementBody, rejectSettlementBody, requestCommissionBody, settlementPreviewQuery, voidInvoiceBody,
} from '@unigate/validation';
import { registry, successEnvelope } from '@/docs/registry.js';

const errorRef = z.object({}).openapi({ $ref: '#/components/schemas/ErrorEnvelope' } as never);
const err = (description: string) => ({ description, content: { 'application/json': { schema: errorRef } } });
const ok = <T extends z.ZodTypeAny>(schema: T, name: string, description = 'OK') => ({ description, content: { 'application/json': { schema: successEnvelope(schema, name) } } });
const json = <T extends z.ZodTypeAny>(schema: T) => ({ content: { 'application/json': { schema } } });
const bearer = [{ bearerAuth: [] }];
const money = z.string().regex(/^-?\d+\.\d{2}$/);
const rate = z.string().regex(/^\d+\.\d{4}$/);
const idem = z.object({ 'idempotency-key': z.string().uuid() });
const ts = z.string().datetime();
const day = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);

const rule = z.object({ id: z.string().uuid(), name: z.string(), scope: z.string(), vehicleCategoryId: z.string().uuid().nullable(), ownerProfileId: z.string().uuid().nullable(), transportType: z.string().nullable(), calculationType: z.string(), percentageRate: money.nullable().openapi({ description: 'Percent 0–100' }), fixedAmount: money.nullable(), basis: z.string(), minAmount: money.nullable(), maxAmount: money.nullable(), currency: z.string(), priority: z.number().int(), effectiveFrom: ts, effectiveTo: ts.nullable(), isActive: z.boolean(), createdAt: ts, updatedAt: ts }).openapi('CommissionRule');
const preview = z.object({ source: z.enum(['RULE', 'OVERRIDE', 'NONE']), type: z.string(), value: money.nullable(), basis: z.string().nullable(), ruleId: z.string().uuid().nullable(), ruleName: z.string().nullable(), grossAmount: money, vatAmount: money, netOfVatAmount: money, commissionAmount: money, commissionVatAmount: money, ownerNetAmount: money, vatTreatment: z.string(), currency: z.string() }).openapi('CommissionPreview');
const effective = z.object({ type: z.string(), value: money.nullable(), basis: z.string().nullable(), source: z.string() });
const requestCommission = z.object({ tripRequestId: z.string().uuid(), override: z.object({ type: z.string(), value: money.nullable(), basis: z.string().nullable(), reason: z.string().nullable(), setByUserId: z.string().uuid().nullable(), setAt: ts.nullable() }).nullable(), effectiveCommission: effective.nullable(), bidsExist: z.boolean() }).openapi('RequestCommission');
const earningsRow = z.object({ key: z.string(), label: z.string().nullable(), bookingCount: z.number().int(), grossAmount: money, commissionAmount: money, commissionVatAmount: money, ownerNetAmount: money });
const earnings = z.object({ groupBy: z.string(), currency: z.string(), rows: z.array(earningsRow), totals: earningsRow.omit({ key: true, label: true }) }).openapi('CommissionEarnings');

const settlement = z.object({ id: z.string().uuid(), settlementNumber: z.string(), ownerProfileId: z.string().uuid(), ownerName: z.string().nullable(), periodStart: ts, periodEnd: ts, grossAmount: money, commissionAmount: money, adjustmentsAmount: money, netPayableAmount: money, currency: z.string(), status: z.string(), bankAccount: z.object({ id: z.string().uuid(), bankName: z.string(), ibanLast4: z.string(), accountHolderName: z.string() }).nullable().openapi({ description: 'ibanLast4 only — never the IBAN' }), paymentReference: z.string().nullable(), approvedByUserId: z.string().uuid().nullable(), paidAt: ts.nullable(), notes: z.string().nullable(), lineCount: z.number().int(), createdAt: ts, updatedAt: ts }).openapi('Settlement');
const settlementLine = z.object({ id: z.string().uuid(), settlementId: z.string().uuid(), bookingId: z.string().uuid().nullable(), bookingNumber: z.string().nullable(), lineType: z.string(), amount: money, currency: z.string(), description: z.string(), holdReason: z.string(), heldSince: ts.nullable(), releasedAt: ts.nullable(), eligibleAt: ts.nullable(), createdAt: ts }).openapi('SettlementLine');
const settlementPreview = z.object({ ownerProfileId: z.string().uuid(), periodStart: ts, periodEnd: ts, currency: z.string(), eligible: z.array(z.object({ bookingId: z.string().uuid(), bookingNumber: z.string(), completedAt: ts.nullable(), eligibleAt: ts, grossAmount: money, deductions: money, ownerNetAmount: money })), held: z.array(z.object({ bookingId: z.string().uuid(), bookingNumber: z.string(), completedAt: ts.nullable(), eligibleAt: ts, holdReason: z.string(), ownerNetAmount: money })), grossAmount: money, commissionAmount: money, adjustmentsAmount: money, netPayableAmount: money, minimumPayoutAmount: money, belowMinimum: z.boolean() }).openapi('SettlementPreview');
const ownerBalance = z.object({ ownerProfileId: z.string().uuid(), accountCode: z.literal('OWNER_PAYABLE'), balance: money, currency: z.string(), inFlightSettlements: money, asOf: ts }).openapi('OwnerBalance');
const ledgerEntry = z.object({ id: z.string().uuid(), accountCode: z.string(), accountType: z.string(), direction: z.enum(['DEBIT', 'CREDIT']), amount: money, currency: z.string(), ownerProfileId: z.string().uuid().nullable(), customerProfileId: z.string().uuid().nullable() });
const ledgerGroup = z.object({ transactionGroupId: z.string().uuid(), description: z.string(), occurredAt: ts, bookingId: z.string().uuid().nullable(), paymentId: z.string().uuid().nullable(), refundId: z.string().uuid().nullable(), settlementId: z.string().uuid().nullable(), invoiceId: z.string().uuid().nullable(), entries: z.array(ledgerEntry), debitTotal: money, creditTotal: money }).openapi('LedgerGroup', { description: 'One balanced posting; debitTotal always equals creditTotal' });

const einvoice = z.object({ einvoiceUuid: z.string().uuid().nullable(), icv: z.number().int().nullable(), invoiceHash: z.string().nullable(), previousInvoiceHash: z.string().nullable(), qrCodeTlv: z.string().nullable(), clearanceStatus: z.string(), clearanceSubmittedAt: ts.nullable(), clearanceCompletedAt: ts.nullable(), clearanceAttemptCount: z.number().int(), xmlDocumentId: z.string().uuid().nullable(), clearedXmlDocumentId: z.string().uuid().nullable(), lastErrorCode: z.string().nullable() }).openapi('InvoiceEinvoice', { description: 'Never a cryptographic stamp, never credentials, never the raw authority response' });
const invoice = z.object({ id: z.string().uuid(), invoiceNumber: z.string(), invoiceType: z.string(), issuedToCustomerProfileId: z.string().uuid(), corporateCustomerProfileId: z.string().uuid().nullable(), buyerName: z.string().nullable(), correctsInvoiceId: z.string().uuid().nullable(), correctsInvoiceNumber: z.string().nullable(), billingPeriodStart: day.nullable(), billingPeriodEnd: day.nullable(), sellerVatNumber: z.string(), buyerVatNumber: z.string().nullable(), lineGranularity: z.string(), subtotalAmount: money, vatAmount: money, totalAmount: money, paidAmount: money, outstandingAmount: money, currency: z.string(), issueDate: day, supplyDate: day, dueDate: day, status: z.string(), lineCount: z.number().int(), einvoice, pdfDocumentId: z.string().uuid().nullable(), createdAt: ts, updatedAt: ts }).openapi('Invoice');
const invoiceLine = z.object({ id: z.string().uuid(), invoiceId: z.string().uuid(), lineType: z.string(), tripRequestId: z.string().uuid().nullable(), requestNumber: z.string().nullable(), bookingId: z.string().uuid().nullable(), bookingNumber: z.string().nullable(), bookingIds: z.array(z.string().uuid()), descriptionEn: z.string(), descriptionAr: z.string(), quantity: money, unitAmount: money, netAmount: money, vatRate: rate, vatAmount: money, totalAmount: money, vatCategory: z.string(), sortOrder: z.number().int() }).openapi('InvoiceLine');
const generateResult = z.object({ periodStart: day, periodEnd: day, customersConsidered: z.number().int(), invoices: z.array(z.object({ invoiceId: z.string().uuid(), invoiceNumber: z.string(), customerProfileId: z.string().uuid(), invoiceType: z.string(), status: z.string(), bookingCount: z.number().int(), totalAmount: money })), skipped: z.array(z.object({ customerProfileId: z.string().uuid(), reason: z.string() })) }).openapi('InvoiceGenerateResult');
const clearanceItem = z.object({ invoiceId: z.string().uuid(), invoiceNumber: z.string(), invoiceType: z.string(), status: z.string(), clearanceStatus: z.string(), clearanceSubmittedAt: ts.nullable(), attemptCount: z.number().int(), ageSeconds: z.number().int(), lastErrorCode: z.string().nullable(), buyer: z.object({ customerProfileId: z.string().uuid(), name: z.string().nullable(), vatNumber: z.string().nullable() }) }).openapi('ClearanceQueueItem');

const expense = z.object({ id: z.string().uuid(), ownerProfileId: z.string().uuid(), vehicleId: z.string().uuid().nullable(), vehiclePlate: z.string().nullable(), driverProfileId: z.string().uuid().nullable(), tripId: z.string().uuid().nullable(), expenseCategoryId: z.string().uuid(), categoryCode: z.string(), amount: money, vatAmount: money, totalAmount: money, currency: z.string(), expenseDate: day, description: z.string().nullable(), vendorName: z.string().nullable(), odometerKm: z.number().int().nullable(), receiptDocumentId: z.string().uuid().nullable(), isReimbursable: z.boolean(), isLocked: z.boolean(), createdAt: ts, updatedAt: ts }).openapi('Expense');
const expenseSummary = z.object({ groupBy: z.enum(['category', 'vehicle', 'month']), currency: z.string(), rows: z.array(z.object({ key: z.string(), label: z.string().nullable(), count: z.number().int(), amount: money, vatAmount: money, totalAmount: money })), totals: z.object({ count: z.number().int(), amount: money, vatAmount: money, totalAmount: money }) }).openapi('ExpenseSummary');

// ── commissions ──────────────────────────────────────────────────────────────
registry.registerPath({ method: 'get', path: '/commissions/rules', tags: ['commissions'], summary: 'Commission rules (commissions.read)', security: bearer, request: { query: listCommissionRulesQuery }, responses: { 200: ok(z.array(rule), 'CommissionRuleListEnvelope', 'OK — paginated') } });
registry.registerPath({ method: 'post', path: '/commissions/rules', tags: ['commissions'], summary: 'Create a rule (commissions.manage). Exactly one active GLOBAL rule may exist; percentages are percent on the API and fractions in storage', security: bearer, request: { body: json(createCommissionRuleBody) }, responses: { 201: ok(rule, 'CommissionRuleEnvelope', 'Created'), 409: err('COMMISSION_RULE_OVERLAP') } });
registry.registerPath({ method: 'post', path: '/commissions/rules/preview', tags: ['commissions'], summary: 'Dry run: which path resolves (RULE | OVERRIDE | NONE) and the split for a VAT-inclusive gross. No writes', security: bearer, request: { body: json(commissionPreviewBody) }, responses: { 200: ok(preview, 'CommissionPreviewEnvelope') } });
registry.registerPath({ method: 'get', path: '/commissions/earnings', tags: ['commissions'], summary: 'Aggregated commission: an owner sees what was deducted from their bookings; reports.financial.read opens every owner', security: bearer, request: { query: commissionEarningsQuery }, responses: { 200: ok(earnings, 'CommissionEarningsEnvelope') } });
registry.registerPath({ method: 'get', path: '/commissions/rules/{id}', tags: ['commissions'], summary: 'One rule', security: bearer, request: { params: idParams }, responses: { 200: ok(rule, 'CommissionRuleEnvelope'), 404: err('NOT_FOUND') } });
registry.registerPath({ method: 'patch', path: '/commissions/rules/{id}', tags: ['commissions'], summary: 'Edit a rule — never rewrites history (snapshots hold their own copy). Deactivating the last GLOBAL rule → 422', security: bearer, request: { params: idParams, body: json(patchCommissionRuleBody) }, responses: { 200: ok(rule, 'CommissionRuleEnvelope'), 409: err('COMMISSION_RULE_OVERLAP'), 422: err('COMMISSION_GLOBAL_RULE_REQUIRED') } });
registry.registerPath({ method: 'delete', path: '/commissions/rules/{id}', tags: ['commissions'], summary: 'Deactivate a rule (rules are referenced by snapshots and never physically removed)', security: bearer, request: { params: idParams }, responses: { 204: { description: 'Deactivated' }, 422: err('COMMISSION_GLOBAL_RULE_REQUIRED') } });
registry.registerPath({ method: 'get', path: '/trip-requests/{id}/commission', tags: ['commissions'], summary: 'The request-level override and the effective commission the next award would charge', security: bearer, request: { params: idParams }, responses: { 200: ok(requestCommission, 'RequestCommissionEnvelope') } });
registry.registerPath({ method: 'patch', path: '/trip-requests/{id}/commission', tags: ['commissions'], summary: 'Per-trip admin decision (commissions.override): set or clear the override. Once bids exist it may only lower the commission', security: bearer, request: { params: idParams, body: json(requestCommissionBody) }, responses: { 200: ok(requestCommission, 'RequestCommissionEnvelope'), 422: err('COMMISSION_OVERRIDE_INVALID / COMMISSION_OVERRIDE_AFTER_BIDS / COMMISSION_OVERRIDE_LOCKED') } });

// ── settlements + ledger ─────────────────────────────────────────────────────
registry.registerPath({ method: 'get', path: '/settlements', tags: ['settlements'], summary: 'Own settlements (owner) or all (settlements.create)', security: bearer, request: { query: listSettlementsQuery }, responses: { 200: ok(z.array(settlement), 'SettlementListEnvelope', 'OK — paginated') } });
registry.registerPath({ method: 'get', path: '/settlements/preview', tags: ['settlements'], summary: 'Dry run: eligible and held bookings, totals, minimum-payout check. Owners use it as "pending settlement"', security: bearer, request: { query: settlementPreviewQuery }, responses: { 200: ok(settlementPreview, 'SettlementPreviewEnvelope') } });
registry.registerPath({ method: 'post', path: '/settlements', tags: ['settlements'], summary: 'Build a DRAFT settlement for (owner, period): one BOOKING_EARNING line per eligible booking; the partial unique index forbids double settlement. Idempotency-Key required', security: bearer, request: { headers: idem, body: json(createSettlementBody) }, responses: { 201: ok(settlement, 'SettlementEnvelope', 'Created'), 409: err('SETTLEMENT_BOOKING_ALREADY_SETTLED'), 422: err('SETTLEMENT_NO_ELIGIBLE_LINES / SETTLEMENT_BELOW_MINIMUM') } });
registry.registerPath({ method: 'get', path: '/settlements/{id}', tags: ['settlements'], summary: 'Header, totals and the payout account (ibanLast4)', security: bearer, request: { params: idParams }, responses: { 200: ok(settlement, 'SettlementEnvelope'), 404: err('NOT_FOUND') } });
registry.registerPath({ method: 'get', path: '/settlements/{id}/lines', tags: ['settlements'], summary: 'Lines with per-booking amounts', security: bearer, request: { params: idParams }, responses: { 200: ok(z.array(settlementLine), 'SettlementLineListEnvelope') } });
registry.registerPath({ method: 'post', path: '/settlements/{id}/lines', tags: ['settlements'], summary: 'Add an ADJUSTMENT / PENALTY line while DRAFT (settlements.create)', security: bearer, request: { params: idParams, body: json(addSettlementLineBody) }, responses: { 201: ok(settlementLine, 'SettlementLineEnvelope', 'Created'), 422: err('SETTLEMENT_INVALID_TRANSITION') } });
registry.registerPath({ method: 'post', path: '/settlements/{id}/submit', tags: ['settlements'], summary: 'DRAFT → PENDING_APPROVAL (or straight to APPROVED under settlement.requires_approval=false / auto_approve_below_amount)', security: bearer, request: { params: idParams }, responses: { 200: ok(settlement, 'SettlementEnvelope'), 422: err('SETTLEMENT_INVALID_TRANSITION') } });
registry.registerPath({ method: 'post', path: '/settlements/{id}/approve', tags: ['settlements'], summary: 'PENDING_APPROVAL → APPROVED — four-eyes: approver ≠ submitter', security: bearer, request: { params: idParams, body: json(approveSettlementBody) }, responses: { 200: ok(settlement, 'SettlementEnvelope'), 422: err('SETTLEMENT_FOUR_EYES / SETTLEMENT_INVALID_TRANSITION') } });
registry.registerPath({ method: 'post', path: '/settlements/{id}/reject', tags: ['settlements'], summary: '→ DRAFT with a reason', security: bearer, request: { params: idParams, body: json(rejectSettlementBody) }, responses: { 200: ok(settlement, 'SettlementEnvelope'), 422: err('SETTLEMENT_INVALID_TRANSITION') } });
registry.registerPath({ method: 'post', path: '/settlements/{id}/pay', tags: ['settlements'], summary: '202 — APPROVED → PAID on the BANK_TRANSFER rail: records the transfer reference, posts DEBIT OWNER_PAYABLE / CREDIT CASH_BANK. Needs a verified payout account past its cool-off. Idempotency-Key required', security: bearer, request: { headers: idem, params: idParams, body: json(paySettlementBody) }, responses: { 202: ok(settlement, 'SettlementEnvelope', 'Accepted'), 422: err('SETTLEMENT_BANK_ACCOUNT_MISSING (details.reason MISSING | UNVERIFIED | COOLOFF) / SETTLEMENT_INVALID_TRANSITION'), 501: err('SETTLEMENT_PAYOUT_RAIL_NOT_AVAILABLE') } });
registry.registerPath({ method: 'get', path: '/ledger/entries', tags: ['ledger'], summary: 'Append-only ledger grouped by transaction (ledger.read)', security: bearer, request: { query: listLedgerEntriesQuery }, responses: { 200: ok(z.array(ledgerGroup), 'LedgerGroupListEnvelope', 'OK — paginated over groups') } });
registry.registerPath({ method: 'get', path: '/ledger/balances/owners/{ownerProfileId}', tags: ['ledger'], summary: 'OWNER_PAYABLE balance = Σ credits − Σ debits, plus settlements in flight', security: bearer, request: { params: ownerIdParams }, responses: { 200: ok(ownerBalance, 'OwnerBalanceEnvelope') } });

// ── invoices ─────────────────────────────────────────────────────────────────
registry.registerPath({ method: 'get', path: '/invoices', tags: ['invoices'], summary: 'Own invoices (buyer) or all (invoices.issue)', security: bearer, request: { query: listInvoicesQuery }, responses: { 200: ok(z.array(invoice), 'InvoiceListEnvelope', 'OK — paginated') } });
registry.registerPath({ method: 'post', path: '/invoices', tags: ['invoices'], summary: 'Issue a single-booking invoice for a COMPLETED booking. Type resolved from the buyer’s VAT number; gapless number + ICV minted in the transaction; a standard invoice returns PENDING_CLEARANCE. Idempotency-Key required', security: bearer, request: { headers: idem, body: json(createInvoiceBody) }, responses: { 201: ok(invoice, 'InvoiceEnvelope', 'Created'), 409: err('INVOICE_BOOKING_ALREADY_BILLED'), 422: err('INVOICE_BOOKING_NOT_BILLABLE / INVOICE_SELLER_VAT_NOT_CONFIGURED'), 503: err('CLEARANCE_PROVIDER_UNAVAILABLE — the invoice exists in PENDING_CLEARANCE; the retry job re-presents it') } });
registry.registerPath({ method: 'post', path: '/admin/invoices/generate', tags: ['invoices'], summary: '202 — billing cycle: one consolidated invoice per customer for every unbilled COMPLETED INVOICED booking in the period (ORDER or BOOKING lines)', security: bearer, request: { headers: idem, body: json(generateInvoicesBody) }, responses: { 202: ok(generateResult, 'InvoiceGenerateResultEnvelope', 'Accepted'), 422: err('INVOICE_SELLER_VAT_NOT_CONFIGURED') } });
registry.registerPath({ method: 'get', path: '/admin/invoices/clearance-queue', tags: ['invoices'], summary: 'Everything not yet through clearance, oldest first', security: bearer, request: { query: clearanceQueueQuery }, responses: { 200: ok(z.array(clearanceItem), 'ClearanceQueueEnvelope', 'OK — paginated') } });
registry.registerPath({ method: 'post', path: '/admin/invoices/{id}/retry-clearance', tags: ['invoices'], summary: '202 — re-present the same document (same number, same ICV)', security: bearer, request: { params: idParams }, responses: { 202: ok(invoice, 'InvoiceEnvelope', 'Accepted'), 409: err('INVOICE_ALREADY_CLEARED') } });
registry.registerPath({ method: 'get', path: '/invoices/{id}', tags: ['invoices'], summary: 'Invoice header with the e-invoicing block (readable at every status)', security: bearer, request: { params: idParams }, responses: { 200: ok(invoice, 'InvoiceEnvelope'), 404: err('NOT_FOUND') } });
registry.registerPath({ method: 'get', path: '/invoices/{id}/lines', tags: ['invoices'], summary: 'Lines in sort order (paginated)', security: bearer, request: { params: idParams, query: listInvoiceLinesQuery }, responses: { 200: ok(z.array(invoiceLine), 'InvoiceLineListEnvelope', 'OK — paginated') } });
registry.registerPath({ method: 'get', path: '/invoices/{id}/pdf-url', tags: ['invoices'], summary: 'Signed URL for the rendered document. 409 while PENDING clearance, 422 when REJECTED; rendering itself is not yet wired (501)', security: bearer, request: { params: idParams }, responses: { 409: err('INVOICE_NOT_CLEARED'), 422: err('INVOICE_CLEARANCE_REJECTED'), 501: err('INVOICE_RENDERING_NOT_AVAILABLE') } });
registry.registerPath({ method: 'get', path: '/invoices/{id}/xml', tags: ['invoices'], summary: 'Signed URL for the cleared UBL XML. 404 when clearance was NOT_REQUIRED; same gates as pdf-url', security: bearer, request: { params: idParams }, responses: { 404: err('NOT_FOUND'), 409: err('INVOICE_NOT_CLEARED'), 501: err('INVOICE_RENDERING_NOT_AVAILABLE') } });
registry.registerPath({ method: 'post', path: '/invoices/{id}/void', tags: ['invoices'], summary: 'DRAFT / CLEARANCE_FAILED / PENDING_CLEARANCE, or ISSUED/OVERDUE while NOT_REQUIRED → VOID. Refused once money was received or the authority holds it. Number never reused; bookings become billable again', security: bearer, request: { params: idParams, body: json(voidInvoiceBody) }, responses: { 200: ok(invoice, 'InvoiceEnvelope'), 409: err('INVOICE_ALREADY_CLEARED'), 422: err('INVOICE_NOT_VOIDABLE') } });
registry.registerPath({ method: 'post', path: '/invoices/{id}/credit-note', tags: ['invoices'], summary: 'Linked CREDIT_NOTE reducing an issued invoice (all or per line); own number + ICV; reverses CUSTOMER_RECEIVABLE', security: bearer, request: { headers: idem, params: idParams, body: json(creditNoteBody) }, responses: { 201: ok(invoice, 'InvoiceEnvelope', 'Created — the credit note'), 422: err('VALIDATION_FAILED') } });
registry.registerPath({ method: 'post', path: '/invoices/{id}/debit-note', tags: ['invoices'], summary: 'Linked DEBIT_NOTE increasing an issued invoice — itself payable, credit-checked for corporate buyers', security: bearer, request: { headers: idem, params: idParams, body: json(debitNoteBody) }, responses: { 201: ok(invoice, 'InvoiceEnvelope', 'Created — the debit note'), 422: err('VALIDATION_FAILED / RULE_CREDIT_LIMIT_EXCEEDED') } });

// ── expenses ─────────────────────────────────────────────────────────────────
registry.registerPath({ method: 'get', path: '/expenses', tags: ['expenses'], summary: 'Own expenses (owner) or all (expenses.read_any)', security: bearer, request: { query: listExpensesQuery }, responses: { 200: ok(z.array(expense), 'ExpenseListEnvelope', 'OK — paginated') } });
registry.registerPath({ method: 'get', path: '/expenses/summary', tags: ['expenses'], summary: 'Totals by category, vehicle or month', security: bearer, request: { query: expenseSummaryQuery }, responses: { 200: ok(expenseSummary, 'ExpenseSummaryEnvelope') } });
registry.registerPath({ method: 'post', path: '/expenses', tags: ['expenses'], summary: 'Record an expense (net + VAT); references resolve under the owner’s scope', security: bearer, request: { body: json(createExpenseBody) }, responses: { 201: ok(expense, 'ExpenseEnvelope', 'Created'), 422: err('VALIDATION_FAILED') } });
registry.registerPath({ method: 'get', path: '/expenses/{id}', tags: ['expenses'], summary: 'One expense', security: bearer, request: { params: idParams }, responses: { 200: ok(expense, 'ExpenseEnvelope'), 404: err('NOT_FOUND') } });
registry.registerPath({ method: 'patch', path: '/expenses/{id}', tags: ['expenses'], summary: 'Edit — 409 EXPENSE_IMMUTABLE once inside a PAID settlement period', security: bearer, request: { params: idParams, body: json(patchExpenseBody) }, responses: { 200: ok(expense, 'ExpenseEnvelope'), 409: err('EXPENSE_IMMUTABLE') } });
registry.registerPath({ method: 'delete', path: '/expenses/{id}', tags: ['expenses'], summary: 'Soft delete — same immutability guard', security: bearer, request: { params: idParams }, responses: { 204: { description: 'Deleted' }, 409: err('EXPENSE_IMMUTABLE') } });
