/**
 * Error classes → HTTP status (api.md §3.1) and the platform-level error codes shared by
 * every module. Module-specific codes (BID_*, BOOKING_*, …) are declared beside the module
 * that raises them, but every code the API can emit is a member of `ErrorCode` so the
 * OpenAPI spec and the web client's interceptor stay exhaustive.
 */

export const ERROR_CLASS_STATUS = {
  ValidationError: 422,
  UnauthorizedError: 401,
  ForbiddenError: 403,
  NotFoundError: 404,
  ConflictError: 409,
  BusinessRuleError: 422,
  RateLimitError: 429,
  BadRequestError: 400,
  NotImplementedError: 501,
  UpstreamError: 502,
  ServiceUnavailableError: 503,
  UpstreamTimeoutError: 504,
  AppError: 500,
} as const;

export type ErrorClassName = keyof typeof ERROR_CLASS_STATUS;

/** Platform-level codes (api.md §4.1–4.3). Domain codes are added by modules as they land. */
export const PLATFORM_ERROR_CODES = [
  // auth
  'AUTH_REQUIRED',
  'AUTH_INVALID_TOKEN',
  'AUTH_TOKEN_EXPIRED',
  'AUTH_TOKEN_REVOKED',
  'AUTH_SESSION_REVOKED',
  'AUTH_INVALID_CREDENTIALS',
  'AUTH_ACCOUNT_SUSPENDED',
  'AUTH_ACCOUNT_NOT_VERIFIED',
  'AUTH_STEP_UP_REQUIRED',
  'AUTH_OTP_INVALID',
  'AUTH_OTP_EXPIRED',
  'AUTH_OTP_THROTTLED',
  'AUTH_CSRF_INVALID',
  // permission
  'PERM_DENIED',
  // validation & platform
  'VALIDATION_FAILED',
  'MALFORMED_JSON',
  'UNSUPPORTED_MEDIA_TYPE',
  'PAYLOAD_TOO_LARGE',
  'NOT_FOUND',
  'ROUTE_NOT_FOUND',
  'METHOD_NOT_ALLOWED',
  'CONFLICT',
  'RATE_LIMITED',
  'IDEMPOTENCY_KEY_REQUIRED',
  'IDEMPOTENCY_KEY_INVALID',
  'IDEMPOTENCY_KEY_REUSED',
  'IDEMPOTENCY_REQUEST_IN_PROGRESS',
  'SETTINGS_KEY_IMMUTABLE',
  'SETTINGS_VALUE_INVALID',
  'VERTICAL_NOT_ENABLED',
  'INTERNAL_ERROR',
  'SERVICE_UNAVAILABLE',
  'UPSTREAM_TIMEOUT',
  'PAYMENT_GATEWAY_ERROR',
  'GEO_PROVIDER_ERROR',
  'CLEARANCE_PROVIDER_UNAVAILABLE',
] as const;

export type PlatformErrorCode = (typeof PLATFORM_ERROR_CODES)[number];

/** iam domain codes (api.md §4.1–4.2). */
export const AUTH_ERROR_CODES = [
  'AUTH_TOKEN_MISSING',
  'AUTH_REFRESH_EXPIRED',
  'AUTH_REFRESH_REUSE_DETECTED',
  'AUTH_PASSWORD_CHANGED',
  'AUTH_ACCOUNT_LOCKED',
  'AUTH_PHONE_NOT_VERIFIED',
  'AUTH_EMAIL_NOT_VERIFIED',
  'AUTH_IDENTIFIER_TAKEN',
  'OWNER_SELF_REGISTRATION_DISABLED',
  'AUTH_OTP_MAX_ATTEMPTS',
  'AUTH_CSRF_HEADER_MISSING',
  'AUTH_CSRF_ORIGIN_MISMATCH',
  'AUTH_PASSWORD_POLICY',
  'AUTH_PASSWORD_RESET_INVALID',
  'PERM_SCOPE_VIOLATION',
  'PERM_ROLE_IMMUTABLE',
  'PERM_SELF_MODIFICATION',
  'USER_HAS_ACTIVE_WORK',
] as const;
export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[number];

/** bidding + award codes (api.md §4.6, §6.4). */
export const BIDDING_ERROR_CODES = [
  'BID_AMOUNT_INVALID',
  'BID_VALIDITY_INVALID',
  'BID_NOT_ELIGIBLE',
  'BID_DUPLICATE_VEHICLE',
  'BID_LIMIT_REACHED',
  'BID_INVALID_TRANSITION',
  'BID_EXPIRED',
  'BID_VEHICLE_UNAVAILABLE',
  'TRIP_REQUEST_NOT_OPEN',
  'TRIP_REQUEST_BIDDING_WINDOW_CLOSED',
  'TRIP_REQUEST_REMAINDER_CLOSED',
  'TRIP_REQUEST_FULLY_AWARDED',
  'RULE_PARTIAL_AWARD_NOT_ALLOWED',
  'RULE_AWARD_SET_INCOMPLETE',
  'RULE_CREDIT_LIMIT_EXCEEDED',
  'RULE_CREDIT_NOT_APPROVED',
  'VEHICLE_NOT_DISPATCHABLE',
  'OWNER_NOT_APPROVED',
  'OWNER_DOCUMENTS_INCOMPLETE',
  'OWNER_VERTICAL_IN_USE',
  'VEHICLE_DOCUMENTS_INCOMPLETE',
  'PERMISSION_NOT_HELD',
  'DRIVER_NOT_APPROVED',
  'DRIVER_LICENSE_EXPIRED',
  'COMMISSION_OVERRIDE_FORBIDDEN',
  'FINANCIAL_SNAPSHOT_UNBALANCED',
  'PLATFORM_FLEET_VEHICLE_REQUIRED',
] as const;
export type BiddingErrorCode = (typeof BIDDING_ERROR_CODES)[number];

/** bookings codes (api.md §4.6, §6.4). */
export const BOOKING_ERROR_CODES = [
  'BOOKING_INVALID_TRANSITION',
  'BOOKING_ALREADY_CANCELLED',
  'BOOKING_CANCELLATION_WINDOW_PASSED',
  'BOOKING_PAYMENT_REQUIRED',
  'CANCELLATION_FEE_OVERRIDE_FORBIDDEN',
  'CANCELLATION_FEE_LOCKED',
  'CANCELLATION_REASON_NOT_ALLOWED',
  'DRIVER_NOT_ASSIGNED_TO_VEHICLE',
  'DRIVER_ALREADY_ON_TRIP',
] as const;
export type BookingErrorCode = (typeof BOOKING_ERROR_CODES)[number];

/** payments + refunds + webhooks codes (api.md §4.7, §6.4, §10). */
export const PAYMENT_ERROR_CODES = [
  'PAYMENT_ALREADY_CAPTURED',
  'PAYMENT_ALREADY_PENDING',
  'PAYMENT_AMOUNT_MISMATCH',
  'PAYMENT_DECLINED',
  'PAYMENT_METHOD_UNSUPPORTED',
  'PAYMENT_NOT_REFUNDABLE',
  'PAYMENT_EXPIRED',
  'PAYMENT_INVALID_TRANSITION',
  'PAYMENT_RETURN_URL_NOT_ALLOWED',
  'INVOICE_PAYMENTS_NOT_AVAILABLE',
  'REFUND_EXCEEDS_CAPTURED',
  'REFUND_ALREADY_PROCESSED',
  'REFUND_INVALID_TRANSITION',
  'REFUND_FOUR_EYES',
  'WEBHOOK_SIGNATURE_INVALID',
  'WEBHOOK_UNKNOWN_PROVIDER',
  'WEBHOOK_REPLAY_WINDOW',
  'LEDGER_UNBALANCED',
] as const;
export type PaymentErrorCode = (typeof PAYMENT_ERROR_CODES)[number];

/** trips + tracking codes (api.md §4.8, §6.4). */
export const TRIP_ERROR_CODES = [
  'TRIP_INVALID_TRANSITION',
  'TRIP_NOT_ACTIVE',
  'TRIP_ALREADY_COMPLETED',
  'TRIP_PROOF_REQUIRED',
  'TRIP_ODOMETER_REQUIRED',
  'TRACKING_SESSION_NOT_ACTIVE',
  'TRACKING_STALE_POINT',
  'TRIP_REGULATORY_DOCUMENT_REQUIRED',
] as const;
export type TripErrorCode = (typeof TRIP_ERROR_CODES)[number];

/** finance codes (api.md §4.9, §8.19–§8.22). */
export const FINANCE_ERROR_CODES = [
  'SETTLEMENT_BOOKING_ALREADY_SETTLED',
  'SETTLEMENT_NO_ELIGIBLE_LINES',
  'SETTLEMENT_INVALID_TRANSITION',
  'SETTLEMENT_FOUR_EYES',
  'SETTLEMENT_BANK_ACCOUNT_MISSING',
  'SETTLEMENT_BELOW_MINIMUM',
  'INVOICE_ALREADY_ISSUED',
  'INVOICE_BOOKING_ALREADY_BILLED',
  'INVOICE_ALREADY_CLEARED',
  'INVOICE_CLEARANCE_REJECTED',
  'INVOICE_NOT_PAYABLE',
  'INVOICE_NOT_VOIDABLE',
  'INVOICE_IMMUTABLE',
  'INVOICE_NOT_CLEARED',
  'INVOICE_BOOKING_NOT_BILLABLE',
  'INVOICE_SELLER_VAT_NOT_CONFIGURED',
  'INVOICE_NOTHING_TO_BILL',
  'COMMISSION_RULE_OVERLAP',
  'COMMISSION_GLOBAL_RULE_REQUIRED',
  'COMMISSION_OVERRIDE_INVALID',
  'COMMISSION_OVERRIDE_AFTER_BIDS',
  'COMMISSION_OVERRIDE_LOCKED',
  'SETTLEMENT_PAYOUT_RAIL_NOT_AVAILABLE',
  'INVOICE_RENDERING_NOT_AVAILABLE',
  'EXPENSE_IMMUTABLE',
] as const;
export type FinanceErrorCode = (typeof FINANCE_ERROR_CODES)[number];

/** maintenance codes (api.md §8.23). */
export const MAINTENANCE_ERROR_CODES = [
  'VEHICLE_CALENDAR_CONFLICT',
  'MAINTENANCE_CALENDAR_CONFLICT',
  'MAINTENANCE_INVALID_TRANSITION',
] as const;
export type MaintenanceErrorCode = (typeof MAINTENANCE_ERROR_CODES)[number];

/** notifications codes (api.md §8.26). */
export const NOTIFICATION_ERROR_CODES = [
  'NOTIFICATION_TEMPLATE_NOT_FOUND',
  'NOTIFICATION_TEMPLATE_VARIABLES_MISSING',
  'NOTIFICATION_CATEGORY_LOCKED',
  'NOTIFICATION_AUDIENCE_EMPTY',
] as const;
export type NotificationErrorCode = (typeof NOTIFICATION_ERROR_CODES)[number];

/** engagement codes (api.md §8.24–8.25). */
export const ENGAGEMENT_ERROR_CODES = [
  'RATING_NOT_ELIGIBLE',
  'RATING_WINDOW_CLOSED',
  'RATING_ALREADY_SUBMITTED',
  'RATING_SUBJECT_INVALID',
  'COMPLAINT_INVALID_TRANSITION',
  'COMPLAINT_RESOLUTION_REQUIRED',
] as const;
export type EngagementErrorCode = (typeof ENGAGEMENT_ERROR_CODES)[number];

/** admin / reporting codes (api.md §8.28–8.30). */
export const ADMIN_ERROR_CODES = [
  'WEBHOOK_SIGNATURE_INVALID',
  'OUTBOX_EVENT_NOT_FAILED',
  'REPORT_NOT_FOUND',
  'REPORT_FORMAT_NOT_AVAILABLE',
  'REPORT_RANGE_TOO_WIDE',
  'EXPORT_NOT_READY',
  'EXPORT_EXPIRED',
] as const;
export type AdminErrorCode = (typeof ADMIN_ERROR_CODES)[number];
