/**
 * Phase 13c — admin & reporting against the real database:
 *   - disputes: a party moves a COMPLETED booking to DISPUTED with a linked complaint (strangers
 *     404); staff resolve as COMPLETED (service stands) — the complaint closes; a refund outcome
 *     without a captured payment is refused
 *   - no-show: ops records an owner no-show with a fee override → NO_SHOW cancellation row, full
 *     customer refund request, owner-payable fee that the settlement preview carries as a
 *     negative adjustment; owners cannot record one
 *   - customer statement: ledger-derived opening / closing balances and ageing buckets
 *   - dashboard KPIs + series, system health / queues, webhook list, outbox retry guard
 *   - audit logs: cursor list, entity history, every read audited, export queued
 *   - reports: registry, inline run scoped to the owner, unsupported filter → 422, financial
 *     codes gated, a CSV export generated by the worker into MinIO and downloadable through a
 *     signed URL (audited)
 */
import { randomUUID } from 'node:crypto';
import request from 'supertest';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { prisma } from '@/database/prisma.js';
import { processNextExport } from '@/modules/reporting/reporting.service.js';
import { TEST_DB, bearer, bootHarness, clearThrottles, createUserWithRoles, loginBearer, teardownHarness, type Harness } from './helpers.js';

const describeDb = TEST_DB ? describe : describe.skip;
const PW = 'admin reporting test passphrase 1';
const hours = (n: number) => new Date(Date.now() + n * 3_600_000).toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000);
const dayStr = (d: Date) => d.toISOString().slice(0, 10);
const pick = <T>(rows: unknown, key: string): T[] => (rows as Record<string, T>[]).map((x) => x[key] as T);
const strs = (rows: unknown, key: string): string[] => pick<string>(rows, key);

describeDb('admin & reporting', () => {
  let h: Harness;
  let admin = '';
  let ops = '';
  let finance = '';
  let customer = '';
  let stranger = '';
  let owner = '';
  let ownerProfileId = '';
  let customerProfileId = '';
  let vehicleId = '';
  let busCategoryId = '';
  let riyadh = '';

  async function approvedVehicle(ownerId: string, categoryId: string): Promise<string> {
    const id = randomUUID();
    await prisma().vehicle.create({ data: { id, ownerProfileId: ownerId, vehicleCategoryId: categoryId, modelYear: 2022, plateNumberEn: `${Math.floor(Math.random() * 9000) + 1000} ADM`, registrationNumber: `REG-${id.slice(0, 6)}`, colorCode: 'WHITE', passengerCapacity: 45, approvalStatus: 'APPROVED', lifecycleStatus: 'ACTIVE' } });
    const types = await prisma().documentType.findMany({ where: { appliesTo: 'VEHICLE', isMandatory: true, isActive: true, OR: [{ transportType: null }, { transportType: 'PASSENGER' }] } });
    for (const t of types) {
      await prisma().document.create({ data: { id: randomUUID(), documentTypeCode: t.code, vehicleId: id, storageBucket: 'test', storageKey: `test/${id}/${t.code}`, originalFilename: 'x.pdf', mimeType: 'application/pdf', sizeBytes: 10n, checksumSha256: 'a'.repeat(64), uploadStatus: 'UPLOADED', verificationStatus: 'VERIFIED', verifiedAt: new Date(), expiryDate: t.requiresExpiry ? new Date('2032-01-01') : null } });
    }
    return id;
  }
  const key = () => randomUUID();
  async function book(pickupInHours: number): Promise<string> {
    const res = await bearer(request(h.app).post('/api/v1/trip-requests'), customer).set('Idempotency-Key', key()).send({
      transportType: 'PASSENGER', vehicleCategoryId: busCategoryId, vehiclesRequired: 1, tripDirection: 'ONE_WAY', publish: true,
      pickup: { addressLine: 'King Khalid International Airport, Riyadh', cityId: riyadh, latitude: 24.95761, longitude: 46.69878 },
      dropoff: { addressLine: 'Al Faisaliah Tower, Riyadh', cityId: riyadh, latitude: 24.69056, longitude: 46.68527 },
      pickupAt: hours(pickupInHours), passengerDetails: { passengerCount: 30, tripPurpose: 'AIRPORT_TRANSFER', luggageCount: 30 },
    });
    expect(res.status, JSON.stringify(res.body)).toBe(201);
    const bid = await bearer(request(h.app).post('/api/v1/bids'), owner).set('Idempotency-Key', key()).send({ tripRequestId: res.body.data.id, vehicleId, baseAmount: '1000.00' });
    expect(bid.status, JSON.stringify(bid.body)).toBe(201);
    const accept = await bearer(request(h.app).post(`/api/v1/bids/${bid.body.data.id}/accept`), customer).set('Idempotency-Key', key()).send({});
    expect(accept.status, JSON.stringify(accept.body)).toBe(201);
    return accept.body.data.booking.id as string;
  }
  async function complete(bookingId: string, ago: number): Promise<void> {
    await prisma().booking.update({ where: { id: bookingId }, data: { status: 'COMPLETED', completedAt: daysAgo(ago) } });
    await prisma().vehicleCalendarEntry.deleteMany({ where: { bookingId } });
  }

  beforeAll(async () => {
    h = await bootHarness();
    await createUserWithRoles('admin@adm.test', PW, ['SUPER_ADMIN']);
    await createUserWithRoles('ops@adm.test', PW, ['OPS_MANAGER']);
    await createUserWithRoles('finance@adm.test', PW, ['FINANCE_OFFICER']);
    const customerUserId = await createUserWithRoles('customer@adm.test', PW, ['CUSTOMER'], 'CUSTOMER');
    await createUserWithRoles('stranger@adm.test', PW, ['CUSTOMER'], 'CUSTOMER');
    const ownerUserId = await createUserWithRoles('owner@adm.test', PW, ['VEHICLE_OWNER'], 'OWNER');
    ownerProfileId = (await prisma().ownerProfile.findFirstOrThrow({ where: { userId: ownerUserId } })).id;
    customerProfileId = (await prisma().customerProfile.findFirstOrThrow({ where: { userId: customerUserId } })).id;
    riyadh = (await prisma().city.findFirstOrThrow({ where: { code: 'RUH' } })).id;
    busCategoryId = (await prisma().vehicleCategory.findFirstOrThrow({ where: { transportType: 'PASSENGER', maxPassengerCapacity: { gte: 40 } }, orderBy: { sortOrder: 'asc' } })).id;
    await prisma().ownerVerticalApproval.create({ data: { id: randomUUID(), ownerProfileId, transportType: 'PASSENGER', status: 'APPROVED' } });
    await prisma().ownerServiceArea.create({ data: { ownerProfileId, cityId: riyadh } });
    vehicleId = await approvedVehicle(ownerProfileId, busCategoryId);
    await clearThrottles();
    admin = (await loginBearer(h.app, 'admin@adm.test', PW)).accessToken;
    ops = (await loginBearer(h.app, 'ops@adm.test', PW)).accessToken;
    finance = (await loginBearer(h.app, 'finance@adm.test', PW)).accessToken;
    customer = (await loginBearer(h.app, 'customer@adm.test', PW)).accessToken;
    await clearThrottles();
    stranger = (await loginBearer(h.app, 'stranger@adm.test', PW)).accessToken;
    owner = (await loginBearer(h.app, 'owner@adm.test', PW)).accessToken;
  });
  afterAll(teardownHarness);

  it('disputes: party opens, staff resolves; no-show with an owner fee feeds the settlement adjustment', async () => {
    const bookingId = await book(48);
    await complete(bookingId, 1);
    expect((await bearer(request(h.app).post(`/api/v1/bookings/${bookingId}/dispute`), stranger).send({ category: 'SERVICE_QUALITY', subject: 'Not my booking', description: 'I should not be able to do this at all.' })).status).toBe(404);
    const disputed = await bearer(request(h.app).post(`/api/v1/bookings/${bookingId}/dispute`), customer).send({ category: 'VEHICLE_CONDITION', subject: 'Air conditioning broken', description: 'The bus had no working air conditioning for the whole airport transfer.' });
    expect(disputed.status, JSON.stringify(disputed.body)).toBe(200);
    expect(disputed.body.data.booking.status).toBe('DISPUTED');
    expect(disputed.body.data.complaint).toMatchObject({ againstType: 'OWNER', againstId: ownerProfileId, bookingId, status: 'OPEN', severity: 'HIGH' });
    expect((await bearer(request(h.app).post(`/api/v1/bookings/${bookingId}/resolve-dispute`), owner).send({ outcome: 'COMPLETED', resolution: 'no' })).status).toBe(403);
    // No captured payment → a refund outcome is refused; resolving as COMPLETED closes the complaint.
    const noPay = await bearer(request(h.app).post(`/api/v1/bookings/${bookingId}/resolve-dispute`), ops).send({ outcome: 'REFUND', resolution: 'Goodwill refund' });
    expect(noPay.status).toBe(422);
    expect(noPay.body.error.code).toBe('PAYMENT_NOT_REFUNDABLE');
    const resolved = await bearer(request(h.app).post(`/api/v1/bookings/${bookingId}/resolve-dispute`), ops).send({ outcome: 'COMPLETED', resolution: 'Owner confirmed the AC fault and offered a 10% credit on the next booking.' });
    expect(resolved.status, JSON.stringify(resolved.body)).toBe(200);
    expect(resolved.body.data.booking.status).toBe('COMPLETED');
    expect(resolved.body.data.complaint).toMatchObject({ status: 'RESOLVED', resolution: 'Owner confirmed the AC fault and offered a 10% credit on the next booking.' });
    expect((await bearer(request(h.app).post(`/api/v1/bookings/${bookingId}/resolve-dispute`), ops).send({ outcome: 'COMPLETED', resolution: 'again' })).body.error.code).toBe('BOOKING_INVALID_TRANSITION');

    // No-show (owner failed to show): ops only; fee override 150.00 charged to the owner; customer refund = full total.
    const b2 = await book(72);
    expect((await bearer(request(h.app).post(`/api/v1/bookings/${b2}/no-show`), owner).set('Idempotency-Key', key()).send({ party: 'CUSTOMER' })).status).toBe(403);
    const noShow = await bearer(request(h.app).post(`/api/v1/bookings/${b2}/no-show`), admin).set('Idempotency-Key', key()).send({ party: 'OWNER', reasonText: 'Vehicle never arrived; driver unreachable.', feeOverride: { type: 'FIXED', value: '150.00', reason: 'Contractual no-show penalty' } });
    expect(noShow.status, JSON.stringify(noShow.body)).toBe(200);
    expect(noShow.body.data.booking.status).toBe('CANCELLED');
    expect(noShow.body.data.cancellation).toMatchObject({ eventType: 'NO_SHOW', reasonCode: 'OWNER_NO_SHOW', feePayer: 'OWNER', cancellationFeeAmount: '150.00', refundAmount: '1150.00', feeSource: 'OVERRIDE' });
    expect(noShow.body.data.refund).toBeNull(); // PENDING_PAYMENT booking: nothing captured, nothing to refund
    expect((await bearer(request(h.app).post(`/api/v1/bookings/${b2}/no-show`), admin).set('Idempotency-Key', key()).send({ party: 'OWNER' })).status).toBe(409);
    // The settlement preview carries the owner fee as a negative adjustment.
    const preview = await bearer(request(h.app).get('/api/v1/settlements/preview'), finance).query({ ownerProfileId, periodStart: daysAgo(30).toISOString(), periodEnd: new Date(Date.now() + 86_400_000).toISOString() });
    expect(preview.status, JSON.stringify(preview.body)).toBe(200);
    expect(preview.body.data.adjustmentsAmount).toBe('-150.00');
  });

  it('customer statement, dashboard, health, queues, webhooks, outbox retry', async () => {
    const st = await bearer(request(h.app).get(`/api/v1/customers/${customerProfileId}/statement`), customer).query({ periodStart: dayStr(daysAgo(30)), periodEnd: dayStr(new Date()) });
    expect(st.status, JSON.stringify(st.body)).toBe(200);
    expect(st.body.data).toMatchObject({ customerProfileId, openingBalance: '0.00', closingBalance: '0.00', currency: 'SAR' });
    expect(st.body.data.ageing).toEqual({ current: '0.00', d1to30: '0.00', d31to60: '0.00', d61to90: '0.00', over90: '0.00' });
    expect((await bearer(request(h.app).get(`/api/v1/customers/${customerProfileId}/statement`), stranger).query({ periodStart: '2026-01-01', periodEnd: '2026-01-31' })).status).toBe(404);

    const dash = await bearer(request(h.app).get('/api/v1/admin/dashboard'), ops).query({ dateFrom: dayStr(daysAgo(7)), dateTo: dayStr(new Date()) });
    expect(dash.status, JSON.stringify(dash.body)).toBe(200);
    expect(dash.body.data.bookings).toBeGreaterThanOrEqual(2);
    expect(dash.body.data.cancelledBookings).toBeGreaterThanOrEqual(1);
    expect(dash.body.data.openComplaints).toBe(0);
    expect(dash.body.meta.computedAt).toBe(dash.body.data.computedAt);
    expect((await bearer(request(h.app).get('/api/v1/admin/dashboard'), ops).query({ dateFrom: dayStr(daysAgo(7)), dateTo: dayStr(new Date()), transportType: 'GOODS' })).body.data.bookings).toBe(0);
    const series = await bearer(request(h.app).get('/api/v1/admin/dashboard/series'), ops).query({ dateFrom: dayStr(daysAgo(2)), dateTo: dayStr(new Date()), bucket: 'day' });
    expect(series.status).toBe(200);
    expect(series.body.data.points.length).toBe(3);
    expect(pick<number>(series.body.data.points, 'bookings').at(-1)).toBeGreaterThanOrEqual(2);
    expect((await bearer(request(h.app).get('/api/v1/admin/dashboard'), customer).query({ dateFrom: '2026-01-01', dateTo: '2026-01-02' })).status).toBe(403);

    const health = await bearer(request(h.app).get('/api/v1/admin/system/health'), admin);
    expect(health.status, JSON.stringify(health.body)).toBe(200);
    expect(health.body.data.checks.database.ok).toBe(true);
    expect(health.body.data.checks.redis.ok).toBe(true);
    expect(health.body.data.migration).toMatch(/^\d{14}_/);
    expect(health.body.data.providers.payment).toBe('mock');
    expect(JSON.stringify(health.body)).not.toMatch(/secret|password|apiKey/i);
    const queues = await bearer(request(h.app).get('/api/v1/admin/system/queues'), admin);
    expect(queues.status).toBe(200);
    expect(strs(queues.body.data.queues, 'name').sort()).toEqual(['events', 'notifications', 'payments']);
    expect((await bearer(request(h.app).get('/api/v1/admin/system/queues'), ops)).status).toBe(403);

    expect((await bearer(request(h.app).get('/api/v1/admin/webhooks/payments'), admin).query({ processingStatus: 'RECEIVED' })).status).toBe(200);
    const bogusReplay = await bearer(request(h.app).post(`/api/v1/admin/webhooks/payments/${randomUUID()}/replay`), admin);
    expect(bogusReplay.status).toBe(404);

    const outboxId = randomUUID();
    await prisma().outboxEvent.create({ data: { id: outboxId, aggregateType: 'test', aggregateId: randomUUID(), eventType: 'test.failed', payload: {}, status: 'FAILED', attemptCount: 10, lastError: 'boom', availableAt: new Date() } });
    const retried = await bearer(request(h.app).post(`/api/v1/admin/outbox/${outboxId}/retry`), admin);
    expect(retried.status, JSON.stringify(retried.body)).toBe(200);
    expect(retried.body.data).toMatchObject({ status: 'PENDING', attemptCount: 0, lastError: null });
    expect((await bearer(request(h.app).post(`/api/v1/admin/outbox/${outboxId}/retry`), admin)).body.error.code).toBe('OUTBOX_EVENT_NOT_FAILED');
    await prisma().outboxEvent.delete({ where: { id: outboxId } });
  });

  it('audit logs: cursor list, entity history, reads audited, export queued', async () => {
    const list = await bearer(request(h.app).get('/api/v1/audit-logs'), admin).query({ pageSize: 2, action: 'booking.' });
    expect(list.status, JSON.stringify(list.body)).toBe(200);
    expect(list.body.data.length).toBe(2);
    expect(list.body.meta.nextCursor).toBeTruthy();
    expect(strs(list.body.data, 'action').every((a) => a.startsWith('booking.'))).toBe(true);
    const next = await bearer(request(h.app).get('/api/v1/audit-logs'), admin).query({ pageSize: 2, action: 'booking.', cursor: list.body.meta.nextCursor });
    expect(next.status).toBe(200);
    expect(strs(next.body.data, 'id')).not.toContain(list.body.data[0].id);
    expect((await bearer(request(h.app).get('/api/v1/audit-logs'), ops)).status).toBe(403);
    const disputedBooking = await prisma().booking.findFirstOrThrow({ where: { customerProfileId, status: 'COMPLETED' } });
    const history = await bearer(request(h.app).get(`/api/v1/audit-logs/entities/booking/${disputedBooking.id}`), admin);
    expect(history.status).toBe(200);
    expect(strs(history.body.data, 'action')).toEqual(expect.arrayContaining(['booking.disputed', 'booking.dispute_resolved']));
    expect(pick<string | null>(history.body.data, 'actorName').every((n) => n === null || typeof n === 'string')).toBe(true);
    expect(await prisma().auditLog.count({ where: { action: 'audit_log.viewed' } })).toBeGreaterThanOrEqual(2);
    expect((await bearer(request(h.app).post('/api/v1/audit-logs/export'), admin).send({ dateFrom: '2026-01-01', dateTo: '2026-06-30' })).status).toBe(400);
    const tooWide = await bearer(request(h.app).post('/api/v1/audit-logs/export'), admin).set('Idempotency-Key', key()).send({ dateFrom: '2026-01-01', dateTo: '2026-06-30' });
    expect(tooWide.status).toBe(422);
    expect(tooWide.body.error.code).toBe('REPORT_RANGE_TOO_WIDE');
    const queued = await bearer(request(h.app).post('/api/v1/audit-logs/export'), admin).set('Idempotency-Key', key()).send({ dateFrom: dayStr(daysAgo(1)), dateTo: dayStr(new Date()), severity: 'NOTICE' });
    expect(queued.status, JSON.stringify(queued.body)).toBe(202);
    expect(queued.body.data).toMatchObject({ reportCode: 'audit-logs', format: 'CSV', status: 'QUEUED' });
  });

  it('reports: registry, scoped inline run, filter validation, financial gating, export → CSV in storage → signed download', async () => {
    const registryRes = await bearer(request(h.app).get('/api/v1/reports'), owner);
    expect(registryRes.status).toBe(200);
    expect(strs(registryRes.body.data, 'code')).toEqual(expect.arrayContaining(['bookings', 'order-fulfilment', 'accounts-receivable-ageing', 'owner-earnings', 'spo-performance']));
    expect(registryRes.body.data.length).toBe(15);
    // Owner runs bookings — own rows only; ops sees the same rows globally; the stranger customer sees none.
    const mine = await bearer(request(h.app).get('/api/v1/reports/bookings'), owner).query({ pageSize: 50 });
    expect(mine.status, JSON.stringify(mine.body)).toBe(200);
    expect(mine.body.meta.totalItems).toBe(2);
    expect(strs(mine.body.meta.columns, 'key')).toContain('bookingNumber');
    expect((await bearer(request(h.app).get('/api/v1/reports/bookings'), stranger).query({})).body.meta.totalItems).toBe(0);
    expect((await bearer(request(h.app).get('/api/v1/reports/bookings'), ops).query({ status: 'CANCELLED' })).body.meta.totalItems).toBe(1);
    const badFilter = await bearer(request(h.app).get('/api/v1/reports/bookings'), ops).query({ colour: 'red' });
    expect(badFilter.status).toBe(422);
    expect(badFilter.body.error.code).toBe('VALIDATION_FAILED');
    expect((await bearer(request(h.app).get('/api/v1/reports/no-such-report'), ops)).status).toBe(404);
    // Financial: ops lacks reports.financial.read; finance has it; owners run owner-earnings on themselves.
    expect((await bearer(request(h.app).get('/api/v1/reports/revenue'), ops)).status).toBe(403);
    const rev = await bearer(request(h.app).get('/api/v1/reports/revenue'), finance).query({ dateFrom: dayStr(daysAgo(7)), dateTo: dayStr(new Date()) });
    expect(rev.status, JSON.stringify(rev.body)).toBe(200);
    expect((await bearer(request(h.app).get('/api/v1/reports/accounts-receivable-ageing'), owner)).status).toBe(403);
    const earnings = await bearer(request(h.app).get('/api/v1/reports/owner-earnings'), owner);
    expect(earnings.status, JSON.stringify(earnings.body)).toBe(200);
    expect(earnings.body.data).toHaveLength(1);
    expect(earnings.body.data[0]).toMatchObject({ completedBookings: 1, penalties: '150.00' });
    const fulfil = await bearer(request(h.app).get('/api/v1/reports/order-fulfilment'), customer);
    expect(fulfil.status, JSON.stringify(fulfil.body)).toBe(200);
    expect(fulfil.body.meta.totalItems).toBe(2);
    expect((fulfil.body.data as { vehiclesCompleted: number; fillRate: number }[]).find((x) => x.vehiclesCompleted === 1)?.fillRate).toBe(1);
    for (const code of ['trips', 'vehicle-utilisation', 'vehicle-maintenance', 'expenses', 'settlements']) {
      const r = await bearer(request(h.app).get(`/api/v1/reports/${code}`), owner);
      expect(r.status, `${code}: ${JSON.stringify(r.body)}`).toBe(200);
    }
    for (const code of ['customer-activity', 'commission', 'payments', 'refunds', 'spo-performance']) {
      const r = await bearer(request(h.app).get(`/api/v1/reports/${code}`), finance);
      expect(r.status, `${code}: ${JSON.stringify(r.body)}`).toBe(200);
    }

    // Export: XLSX refused today; CSV queued, generated by the worker, downloadable through a signed URL (audited).
    expect((await bearer(request(h.app).post('/api/v1/reports/bookings/export'), owner).set('Idempotency-Key', key()).send({ format: 'XLSX' })).body.error.code).toBe('REPORT_FORMAT_NOT_AVAILABLE');
    const job = await bearer(request(h.app).post('/api/v1/reports/bookings/export'), owner).set('Idempotency-Key', key()).send({ format: 'CSV', filters: { status: 'COMPLETED' } });
    expect(job.status, JSON.stringify(job.body)).toBe(202);
    expect(job.body.data.status).toBe('QUEUED');
    expect((await bearer(request(h.app).get(`/api/v1/reports/exports/${job.body.data.id}/download-url`), owner)).body.error.code).toBe('EXPORT_NOT_READY');
    // Two jobs are queued (the audit export above and this one); the worker drains both.
    expect(await processNextExport()).toBe(true);
    expect(await processNextExport()).toBe(true);
    expect(await processNextExport()).toBe(false);
    const done = await bearer(request(h.app).get(`/api/v1/reports/exports/${job.body.data.id}`), owner);
    expect(done.status).toBe(200);
    expect(done.body.data, JSON.stringify(done.body.data)).toMatchObject({ status: 'COMPLETED', rowCount: 1, downloadable: true });
    expect((await bearer(request(h.app).get(`/api/v1/reports/exports/${job.body.data.id}`), stranger)).status).toBe(404);
    const url = await bearer(request(h.app).get(`/api/v1/reports/exports/${job.body.data.id}/download-url`), owner);
    expect(url.status, JSON.stringify(url.body)).toBe(200);
    expect(url.body.data.filename).toMatch(/^bookings-\d{4}-\d{2}-\d{2}-[0-9a-f]{8}\.csv$/);
    const file = await fetch(url.body.data.url);
    expect(file.status).toBe(200);
    const bytes = Buffer.from(await file.arrayBuffer());
    expect([...bytes.subarray(0, 3)]).toEqual([0xef, 0xbb, 0xbf]); // UTF-8 BOM so Excel opens Arabic correctly
    const text = bytes.subarray(3).toString('utf8');
    expect(text).toContain('Booking,Request,Vertical,Status');
    expect(text.split('\r\n').filter(Boolean)).toHaveLength(2);
    expect(text).toContain(',COMPLETED,');
    expect(await prisma().auditLog.count({ where: { action: 'report.export_downloaded', entityId: job.body.data.id } })).toBe(1);
    expect((await bearer(request(h.app).get('/api/v1/reports/exports'), owner)).body.meta.totalItems).toBe(1);
    expect((await bearer(request(h.app).get('/api/v1/reports/exports'), admin)).body.meta.totalItems).toBe(2);
  });
});
