/** OpenAPI registrations for /maintenance (api.md §8.23). */
import { z } from 'zod';
import { cancelMaintenanceRecordBody, completeMaintenanceRecordBody, createMaintenanceRecordBody, createMaintenanceScheduleBody, idParams, listMaintenanceRecordsQuery, listMaintenanceSchedulesQuery, maintenanceDueQuery, patchMaintenanceRecordBody, patchMaintenanceScheduleBody } from '@unigate/validation';
import { registry, successEnvelope } from '@/docs/registry.js';

const errorRef = z.object({}).openapi({ $ref: '#/components/schemas/ErrorEnvelope' } as never);
const err = (description: string) => ({ description, content: { 'application/json': { schema: errorRef } } });
const ok = <T extends z.ZodTypeAny>(schema: T, name: string, description = 'OK') => ({ description, content: { 'application/json': { schema: successEnvelope(schema, name) } } });
const json = <T extends z.ZodTypeAny>(schema: T) => ({ content: { 'application/json': { schema } } });
const bearer = [{ bearerAuth: [] }];
const money = z.string().regex(/^-?\d+\.\d{2}$/);
const ts = z.string().datetime();

const record = z.object({
  id: z.string().uuid(), vehicleId: z.string().uuid(), vehiclePlate: z.string(), ownerProfileId: z.string().uuid(), serviceTypeId: z.string().uuid(), serviceTypeCode: z.string(), serviceTypeNameEn: z.string(), serviceTypeNameAr: z.string(),
  maintenanceKind: z.string(), status: z.string(), scheduledStartAt: ts, scheduledEndAt: ts, actualStartAt: ts.nullable(), actualEndAt: ts.nullable(), odometerKm: z.number().int().nullable(), costAmount: money, vatAmount: money, totalAmount: money, currency: z.string(),
  workshopName: z.string().nullable(), workshopContact: z.string().nullable(), description: z.string().nullable(), partsReplaced: z.array(z.object({ name: z.string(), quantity: z.number().int(), amount: money.nullable() })), nextServiceDate: z.string().nullable(), nextServiceOdometerKm: z.number().int().nullable(),
  calendarEntryId: z.string().uuid().nullable(), documentIds: z.array(z.string().uuid()), createdAt: ts, updatedAt: ts,
}).openapi('MaintenanceRecord');
const schedule = z.object({ id: z.string().uuid(), vehicleId: z.string().uuid(), vehiclePlate: z.string(), ownerProfileId: z.string().uuid(), serviceTypeId: z.string().uuid(), serviceTypeCode: z.string(), serviceTypeNameEn: z.string(), serviceTypeNameAr: z.string(), intervalKm: z.number().int().nullable(), intervalDays: z.number().int().nullable(), lastServiceAt: ts.nullable(), lastServiceOdometerKm: z.number().int().nullable(), nextDueAt: ts.nullable(), nextDueOdometerKm: z.number().int().nullable(), isActive: z.boolean(), createdAt: ts, updatedAt: ts }).openapi('MaintenanceSchedule');
const due = z.object({ scheduleId: z.string().uuid(), vehicleId: z.string().uuid(), vehiclePlate: z.string(), ownerProfileId: z.string().uuid(), serviceTypeCode: z.string(), serviceTypeNameEn: z.string(), serviceTypeNameAr: z.string(), nextDueAt: ts.nullable(), nextDueOdometerKm: z.number().int().nullable(), currentOdometerKm: z.number().int().nullable(), daysUntilDue: z.number().int().nullable(), kmUntilDue: z.number().int().nullable(), overdue: z.boolean() }).openapi('MaintenanceDue');

registry.registerPath({ method: 'get', path: '/maintenance/records', tags: ['maintenance'], summary: 'Maintenance records — own vehicles (owner) or all (maintenance.read_any)', security: bearer, request: { query: listMaintenanceRecordsQuery }, responses: { 200: ok(z.array(record), 'MaintenanceRecordListEnvelope', 'OK — paginated') } });
registry.registerPath({ method: 'post', path: '/maintenance/records', tags: ['maintenance'], summary: 'Create a record; PLANNED / IN_PROGRESS also holds a MAINTENANCE entry on the vehicle calendar in the same transaction (unbookable structurally)', security: bearer, request: { body: json(createMaintenanceRecordBody) }, responses: { 201: ok(record, 'MaintenanceRecordEnvelope', 'Created'), 409: err('MAINTENANCE_CALENDAR_CONFLICT — details.conflicts names the blocking booking / block'), 422: err('VALIDATION_FAILED') } });
registry.registerPath({ method: 'get', path: '/maintenance/records/{id}', tags: ['maintenance'], summary: 'Record + linked documents + calendar entry', security: bearer, request: { params: idParams }, responses: { 200: ok(record, 'MaintenanceRecordEnvelope'), 404: err('NOT_FOUND') } });
registry.registerPath({ method: 'patch', path: '/maintenance/records/{id}', tags: ['maintenance'], summary: 'Costs, workshop, parts, thresholds; a moved window re-attempts the calendar hold (can 409)', security: bearer, request: { params: idParams, body: json(patchMaintenanceRecordBody) }, responses: { 200: ok(record, 'MaintenanceRecordEnvelope'), 409: err('MAINTENANCE_CALENDAR_CONFLICT'), 422: err('MAINTENANCE_INVALID_TRANSITION') } });
registry.registerPath({ method: 'post', path: '/maintenance/records/{id}/start', tags: ['maintenance'], summary: 'PLANNED → IN_PROGRESS; the vehicle goes UNDER_MAINTENANCE', security: bearer, request: { params: idParams }, responses: { 200: ok(record, 'MaintenanceRecordEnvelope'), 422: err('MAINTENANCE_INVALID_TRANSITION') } });
registry.registerPath({ method: 'post', path: '/maintenance/records/{id}/complete', tags: ['maintenance'], summary: '→ COMPLETED: actual end, odometer forward, calendar hold released, vehicle IDLE, matching schedule rolled forward, cost booked as a MAINTENANCE expense', security: bearer, request: { params: idParams, body: json(completeMaintenanceRecordBody) }, responses: { 200: ok(record, 'MaintenanceRecordEnvelope'), 422: err('MAINTENANCE_INVALID_TRANSITION / VALIDATION_FAILED (odometer backwards)') } });
registry.registerPath({ method: 'post', path: '/maintenance/records/{id}/cancel', tags: ['maintenance'], summary: '→ CANCELLED with a reason; releases the hold', security: bearer, request: { params: idParams, body: json(cancelMaintenanceRecordBody) }, responses: { 200: ok(record, 'MaintenanceRecordEnvelope'), 422: err('MAINTENANCE_INVALID_TRANSITION') } });
registry.registerPath({ method: 'delete', path: '/maintenance/records/{id}', tags: ['maintenance'], summary: 'Delete a PLANNED record created in error (maintenance.delete + read_any — staff)', security: bearer, request: { params: idParams }, responses: { 204: { description: 'Deleted' }, 422: err('MAINTENANCE_INVALID_TRANSITION') } });
registry.registerPath({ method: 'get', path: '/maintenance/schedules', tags: ['maintenance'], summary: 'Interval definitions per vehicle', security: bearer, request: { query: listMaintenanceSchedulesQuery }, responses: { 200: ok(z.array(schedule), 'MaintenanceScheduleListEnvelope', 'OK — paginated') } });
registry.registerPath({ method: 'post', path: '/maintenance/schedules', tags: ['maintenance'], summary: 'Create a schedule (km and/or days); the clock starts at the last service or now', security: bearer, request: { body: json(createMaintenanceScheduleBody) }, responses: { 201: ok(schedule, 'MaintenanceScheduleEnvelope', 'Created'), 409: err('CONFLICT — one active schedule per vehicle × service type') } });
registry.registerPath({ method: 'patch', path: '/maintenance/schedules/{id}', tags: ['maintenance'], summary: 'Edit intervals / last service; next-due recomputed', security: bearer, request: { params: idParams, body: json(patchMaintenanceScheduleBody) }, responses: { 200: ok(schedule, 'MaintenanceScheduleEnvelope') } });
registry.registerPath({ method: 'delete', path: '/maintenance/schedules/{id}', tags: ['maintenance'], summary: 'Deactivate a schedule', security: bearer, request: { params: idParams }, responses: { 204: { description: 'Deactivated' } } });
registry.registerPath({ method: 'get', path: '/maintenance/due', tags: ['maintenance'], summary: 'Vehicles past or approaching next_due_at / next_due_odometer_km — the reminder job and the owner dashboard share it', security: bearer, request: { query: maintenanceDueQuery }, responses: { 200: ok(z.array(due), 'MaintenanceDueEnvelope') } });
