/** OpenAPI registrations for /notifications (api.md §8.26). */
import { z } from 'zod';
import { createNotificationTemplateBody, idParams, listNotificationTemplatesQuery, listNotificationsQuery, patchNotificationTemplateBody, previewNotificationTemplateBody, putNotificationPreferencesBody, readAllNotificationsBody, registerDeviceTokenBody, sendNotificationBody } from '@unigate/validation';
import { registry, successEnvelope } from '@/docs/registry.js';

const errorRef = z.object({}).openapi({ $ref: '#/components/schemas/ErrorEnvelope' } as never);
const err = (description: string) => ({ description, content: { 'application/json': { schema: errorRef } } });
const ok = <T extends z.ZodTypeAny>(schema: T, name: string, description = 'OK') => ({ description, content: { 'application/json': { schema: successEnvelope(schema, name) } } });
const json = <T extends z.ZodTypeAny>(schema: T) => ({ content: { 'application/json': { schema } } });
const bearer = [{ bearerAuth: [] }];
const ts = z.string().datetime();

const notification = z.object({ id: z.string().uuid(), templateCode: z.string(), channel: z.string(), category: z.string(), title: z.string().nullable(), body: z.string(), data: z.record(z.string(), z.unknown()), status: z.string(), readAt: ts.nullable(), createdAt: ts }).openapi('Notification');
const unread = z.object({ total: z.number().int(), byCategory: z.record(z.string(), z.number().int()) }).openapi('NotificationUnreadCount');
const preference = z.object({ category: z.string(), channel: z.string(), isEnabled: z.boolean(), isLocked: z.boolean() }).openapi('NotificationPreference');
const template = z.object({ id: z.string().uuid(), code: z.string(), channel: z.string(), locale: z.string(), subject: z.string().nullable(), body: z.string(), variables: z.array(z.string()), category: z.string(), isActive: z.boolean(), version: z.number().int(), createdAt: ts, updatedAt: ts }).openapi('NotificationTemplate');
const preview = z.object({ locale: z.string(), channel: z.string(), subject: z.string().nullable(), body: z.string(), missingVariables: z.array(z.string()) }).openapi('NotificationPreview');
const sendResult = z.object({ templateCode: z.string(), recipients: z.number().int(), queued: z.number().int(), suppressed: z.number().int() }).openapi('NotificationSendResult');

registry.registerPath({ method: 'get', path: '/notifications', tags: ['notifications'], summary: 'In-app inbox (self) — cursor-paginated; meta.nextCursor', security: bearer, request: { query: listNotificationsQuery }, responses: { 200: ok(z.array(notification), 'NotificationListEnvelope') } });
registry.registerPath({ method: 'get', path: '/notifications/unread-count', tags: ['notifications'], summary: 'Unread total and per category (socket fallback poll)', security: bearer, responses: { 200: ok(unread, 'NotificationUnreadCountEnvelope') } });
registry.registerPath({ method: 'post', path: '/notifications/read-all', tags: ['notifications'], summary: 'Mark the inbox read, optionally one category', security: bearer, request: { body: json(readAllNotificationsBody) }, responses: { 200: ok(z.object({ updated: z.number().int() }), 'NotificationReadAllEnvelope') } });
registry.registerPath({ method: 'post', path: '/notifications/{id}/read', tags: ['notifications'], summary: 'Mark one notification read', security: bearer, request: { params: idParams }, responses: { 200: ok(notification, 'NotificationEnvelope'), 404: err('NOT_FOUND') } });
registry.registerPath({ method: 'delete', path: '/notifications/{id}', tags: ['notifications'], summary: 'Remove from the inbox', security: bearer, request: { params: idParams }, responses: { 204: { description: 'Deleted' }, 404: err('NOT_FOUND') } });
registry.registerPath({ method: 'get', path: '/notifications/preferences', tags: ['notifications'], summary: 'Category × channel preferences; locked categories cannot be disabled (FR-NOTIFICATIONS-06)', security: bearer, responses: { 200: ok(z.array(preference), 'NotificationPreferenceListEnvelope') } });
registry.registerPath({ method: 'put', path: '/notifications/preferences', tags: ['notifications'], summary: 'Update preferences', security: bearer, request: { body: json(putNotificationPreferencesBody) }, responses: { 200: ok(z.array(preference), 'NotificationPreferenceListEnvelope'), 422: err('NOTIFICATION_CATEGORY_LOCKED') } });
registry.registerPath({ method: 'post', path: '/notifications/devices', tags: ['notifications'], summary: 'Register a push device token for the actor', security: bearer, request: { body: json(registerDeviceTokenBody) }, responses: { 204: { description: 'Registered' } } });
registry.registerPath({ method: 'delete', path: '/notifications/devices/{token}', tags: ['notifications'], summary: 'Deactivate a push device token', security: bearer, request: { params: z.object({ token: z.string() }) }, responses: { 204: { description: 'Deactivated' } } });
registry.registerPath({ method: 'post', path: '/notifications/send', tags: ['notifications'], summary: 'Ops broadcast / targeted send: template + variables to an audience (userIds, roleCodes, profileTypes); never free text; Idempotency-Key required', security: bearer, request: { body: json(sendNotificationBody) }, responses: { 202: ok(sendResult, 'NotificationSendResultEnvelope', 'Accepted'), 404: err('NOTIFICATION_TEMPLATE_NOT_FOUND'), 422: err('NOTIFICATION_TEMPLATE_VARIABLES_MISSING / NOTIFICATION_AUDIENCE_EMPTY') } });
registry.registerPath({ method: 'get', path: '/notifications/templates', tags: ['notifications'], summary: 'Templates by code, channel, locale, category', security: bearer, request: { query: listNotificationTemplatesQuery }, responses: { 200: ok(z.array(template), 'NotificationTemplateListEnvelope', 'OK — paginated') } });
registry.registerPath({ method: 'post', path: '/notifications/templates', tags: ['notifications'], summary: 'Create a template (code × channel × locale unique)', security: bearer, request: { body: json(createNotificationTemplateBody) }, responses: { 201: ok(template, 'NotificationTemplateEnvelope', 'Created'), 409: err('CONFLICT') } });
registry.registerPath({ method: 'get', path: '/notifications/templates/{id}', tags: ['notifications'], summary: 'Template detail', security: bearer, request: { params: idParams }, responses: { 200: ok(template, 'NotificationTemplateEnvelope'), 404: err('NOT_FOUND') } });
registry.registerPath({ method: 'patch', path: '/notifications/templates/{id}', tags: ['notifications'], summary: 'Edit wording without a deploy; version increments; audited', security: bearer, request: { params: idParams, body: json(patchNotificationTemplateBody) }, responses: { 200: ok(template, 'NotificationTemplateEnvelope'), 404: err('NOT_FOUND') } });
registry.registerPath({ method: 'post', path: '/notifications/templates/{id}/preview', tags: ['notifications'], summary: 'Render against sample variables without sending; lists unfilled placeholders', security: bearer, request: { params: idParams, body: json(previewNotificationTemplateBody) }, responses: { 200: ok(preview, 'NotificationPreviewEnvelope') } });
